version: '3.7'

services:

  redis: 
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  bookmark_service:
    image: bookmark_service:dev
    build: .
    container_name: bookmark_service
    ports:
      - "8080:8080"
    environment:
       - REDIS_ADDR=redis:6379
    volumes:
      - ./public.pem:/app/public.pem:Z
      - ./private.pem:/app/private.pem:Z
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookmark_service
      - PGDATA= /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata 

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
    name: bookmark_service_network