// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenURLservice is an autogenerated mock type for the ShortenURLservice type
type ShortenURLservice struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: ctx, url
func (_m *ShortenURLservice) GetURL(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortlengthURL provides a mock function with given fields: ctx, originURL, expireAt
func (_m *ShortenURLservice) ShortlengthURL(ctx context.Context, originURL string, expireAt int64) (string, error) {
	ret := _m.Called(ctx, originURL, expireAt)

	if len(ret) == 0 {
		panic("no return value specified for ShortlengthURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, originURL, expireAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, originURL, expireAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, originURL, expireAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenURLservice creates a new instance of ShortenURLservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenURLservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenURLservice {
	mock := &ShortenURLservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
