// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/toanuitt/bookmark_service/internal/model"
)

// Userservice is an autogenerated mock type for the Userservice type
type Userservice struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, username, password, displayName, email
func (_m *Userservice) Register(ctx context.Context, username string, password string, displayName string, email string) (*model.User, error) {
	ret := _m.Called(ctx, username, password, displayName, email)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.User, error)); ok {
		return rf(ctx, username, password, displayName, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.User); ok {
		r0 = rf(ctx, username, password, displayName, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, username, password, displayName, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserservice creates a new instance of Userservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Userservice {
	mock := &Userservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
